cp -f abp-filter-parser-cpp/ABPFilterParser.cpp chrome/browser/net/blockers/ABPFilterParser.cpp
cp -f abp-filter-parser-cpp/ABPFilterParser.h chrome/browser/net/blockers/ABPFilterParser.h
cp -f abp-filter-parser-cpp/cosmeticFilter.cpp chrome/browser/net/blockers/cosmeticFilter.cpp
cp -f abp-filter-parser-cpp/cosmeticFilter.h chrome/browser/net/blockers/cosmeticFilter.h
cp -f abp-filter-parser-cpp/filter.cpp chrome/browser/net/blockers/filter.cpp
cp -f abp-filter-parser-cpp/filter.h chrome/browser/net/blockers/filter.h
cp -f abp-filter-parser-cpp/base.h chrome/browser/net/blockers/base.h
cp -f abp-filter-parser-cpp/badFingerprint.h chrome/browser/net/blockers/badFingerprint.h
cp -f abp-filter-parser-cpp/badFingerprints.h chrome/browser/net/blockers/badFingerprints.h
cp -f bloom-filter-cpp/BloomFilter.cpp chrome/browser/net/blockers/BloomFilter.cpp
cp -f bloom-filter-cpp/BloomFilter.h chrome/browser/net/blockers/BloomFilter.h
cp -f bloom-filter-cpp/hashFn.h chrome/browser/net/blockers/hashFn.h
cp -f bloom-filter-cpp/hashFn.cpp chrome/browser/net/blockers/hashFn.cpp
cp -f hashset-cpp/HashSet.cpp chrome/browser/net/blockers/HashSet.cpp
cp -f hashset-cpp/HashSet.h chrome/browser/net/blockers/HashSet.h
cp -f hashset-cpp/HashItem.h chrome/browser/net/blockers/HashItem.h
cp -f tracking-protection/FirstPartyHost.h chrome/browser/net/blockers/FirstPartyHost.h
cp -f tracking-protection/TrackerData.h chrome/browser/net/blockers/TrackerData.h
cp -f tracking-protection/TPParser.h chrome/browser/net/blockers/TPParser.h
cp -f tracking-protection/TPParser.cpp chrome/browser/net/blockers/TPParser.cpp
